packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/postcss': ^4.1.18
  '@trpc/client': ^11.8.1
  '@trpc/react-query': ^11.8.1
  '@trpc/server': ^11.8.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  better-auth: ^1.4.9
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  lucide-react: 0.562.0
  next: ^16.1.1
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  react: ^19.2.3
  react-dom: ^19.2.3
  react-hook-form: 7.69.0
  recharts: 3.6.0
  sonner: 2.0.7
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  zod: ^4.2.1
