import { authClient } from "@/server/auth/client";

export const {
  accountInfo,
  admin,
  changeEmail,
  changePassword,
  deleteUser,
  getAccessToken,
  getSession,
  linkSocial,
  listAccounts,
  listSessions,
  refreshToken,
  requestPasswordReset,
  resetPassword,
  revokeOtherSessions,
  revokeSession,
  revokeSessions,
  sendVerificationEmail,
  signIn,
  signOut,
  signUp,
  twoFactor,
  unlinkAccount,
  updateUser,
  useSession,
  verifyEmail,
} = authClient;
